/*
Do not edit this file manually, it is overwritten every time dlcov
runs, in order to make coverage work for all dart files
*/

// ignore_for_file: unused_import
import 'package:flutter_contacts/generated/proto/index.pbenum.dart';
import 'package:flutter_contacts/generated/proto/index.pbgrpc.dart';
import 'package:flutter_contacts/generated/proto/index.pbjson.dart';
import 'package:flutter_contacts/generated/proto/index.pb.dart';
import 'package:flutter_contacts/themes.dart';
import 'package:flutter_contacts/providers/contacts_provider.dart';
import 'package:flutter_contacts/providers/contact_provider.dart';
import 'package:flutter_contacts/providers/go_router_provider.dart';
import 'package:flutter_contacts/providers/auth_provider.dart';
import 'package:flutter_contacts/providers/language_provider.dart';
import 'package:flutter_contacts/providers/theme_provider.dart';
import 'package:flutter_contacts/repositories/auth_repository.dart';
import 'package:flutter_contacts/repositories/contacts_repository.dart';
import 'package:flutter_contacts/models/contact.dart';
import 'package:flutter_contacts/models/auth_state.dart';
import 'package:flutter_contacts/screens/contacts/favorite_contact_list.dart';
import 'package:flutter_contacts/screens/contacts/contacts_screen.dart';
import 'package:flutter_contacts/screens/contacts/contacts_list.dart';
import 'package:flutter_contacts/screens/contacts_details_screen.dart';
import 'package:flutter_contacts/screens/login_screen.dart';
import 'package:flutter_contacts/main.dart';
import 'package:flutter_contacts/data/dummy_data.dart';
import 'package:flutter_contacts/services/contacts_service.dart';
import 'package:flutter_contacts/widgets/main_draw.dart';
import 'package:flutter_contacts/widgets/new_contact_form.dart';
void main(){}